- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: Install PYMysql Libraries
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9

  - name: Install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: Start and enable  mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.daws82s.fun
    register: mysql_info
    ignore_errors: true

  - name: print the mysql output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup custome password 
    ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"
    when: mysql_info.failed is true 


